### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by vlouvet**
Added verify=False flag to all requests so the requests do not fail due to a self-signed or incorrectly configured certificate.

### CODE REVIEW

**Comment by vlouvet** [comment]
sorry for the confusion, I am new to the pull request process :-)

**Comment by davidgasquez** [comment]
Thanks for the Pull Request @vlouvet! 

Does it works for you after doing this? If that's the case I can make the `verify` variable a parameter so each client can define if it wants verification or not.

**Comment by vlouvet** [comment]
yes it does, thanks David!

**Comment by davidgasquez** [comment]
Merging this then! I'll make it a parameter right away. :smile: 

Thanks again for sending the pull request!

**Pull request merged**
